// <auto-generated />
namespace Realtor_Automation.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class update_relation : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(update_relation));
        
        string IMigrationMetadata.Id
        {
            get { return "202105141158448_update_relation"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
